{
 "title": "RKE2 Lab - Application Pods",
 "tags": [
  "rke2",
  "lab",
  "application",
  "pods"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU par Pod - namespace lab-k8s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "(sum by(namespace,pod) (rate(container_cpu_usage_seconds_total{namespace=\"lab-k8s\", container!=\"\", container!=\"POD\"}[5m]))) * on(namespace,pod) group_left(node) max by (namespace, pod, node) (kube_pod_info{namespace=\"lab-k8s\"})",
     "legendFormat": "{{ pod }} - {{ node }}"
    }
   ]
  },
  {
   "title": "RAM par Pod - namespace lab-k8s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(sum by(namespace,pod) (container_memory_working_set_bytes{namespace=\"lab-k8s\", container!=\"\", container!=\"POD\"})) * on(namespace,pod) group_left(node) max by (namespace, pod, node) (kube_pod_info{namespace=\"lab-k8s\"})",
     "legendFormat": "{{ pod }} - {{ node }}"
    }
   ]
  },
  {
   "title": "CPU PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "(sum by(namespace,pod) (rate(container_cpu_usage_seconds_total{namespace=\"lab-k8s\", pod=~\"pg-lab-postgresql.*\", container!=\"\", container!=\"POD\"}[5m]))) * on(namespace,pod) group_left(node) max by (namespace, pod, node) (kube_pod_info{namespace=\"lab-k8s\"})",
     "legendFormat": "{{ pod }} - {{ node }}"
    }
   ]
  },
  {
   "title": "RAM PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(sum by(namespace,pod) (container_memory_working_set_bytes{namespace=\"lab-k8s\", pod=~\"pg-lab-postgresql.*\", container!=\"\", container!=\"POD\"})) * on(namespace,pod) group_left(node) max by (namespace, pod, node) (kube_pod_info{namespace=\"lab-k8s\"})",
     "legendFormat": "{{ pod }} - {{ node }}"
    }
   ]
  },
  {
   "title": "CPU par composant applicatif",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "(sum by(namespace,pod) (rate(container_cpu_usage_seconds_total{namespace=\"lab-k8s\", pod=~\"blog-back-fpm.*|blog-back-nginx.*|pg-lab-postgresql.*\", container!=\"\", container!=\"POD\"}[5m]))) * on(namespace,pod) group_left(node) max by (namespace, pod, node) (kube_pod_info{namespace=\"lab-k8s\"})",
     "legendFormat": "{{ pod }} - {{ node }}"
    }
   ]
  }
 ]
}