apiVersion: v1
kind: Service
metadata:
  name: blog-back-nginx
  namespace: lab-k8s
  labels:
    app.kubernetes.io/name: blog-back-nginx
    app.kubernetes.io/part-of: blog-back
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: blog-back-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
